### ISSUE TITLE
PyVOL installation issues

### ISSUE THREAD

**Issue by RashedCh** [schlessingerlab/pyvol#11]
Windows 11 Pro
Python 3.10.5
pip 22.1.2 from C:\Python\lib\site-packages\pip (python 3.10)
PyMOL 2.5.2 (Licensed)

I've got the following error message while installing PyVOL : 

Traceback (most recent call last):
  File "C:\PyMOL\lib\site-packages\pmg_tk\startup\pyvol-installer\__init__.py", line 68, in pyvol_window
    refresh_installation_status(form)
  File "C:\PyMOL\lib\site-packages\pmg_tk\startup\pyvol-installer\__init__.py", line 260, in refresh_installation_status
    all_pckgs = subprocess.check_output([sys.executable, "-m", "pip", "list", "--format=json"]).decode('utf-8').strip()
  File "C:\PyMOL\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "C:\PyMOL\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:\\PyMOL\\pythonw.exe', '-m', 'pip', 'list', '--format=json']' returned non-zero exit status 120.

**Comment by gorostiolam** [comment]
I get the same error albeit not while installing PyVOL but while trying to launch it from the Pymol Plugin tab. 

I installed PyVOL from the .zip GUI installer via the Plugin Manager on Pymol. 

I have Pymol 2.5.2 with an educational license in Windows 10 
Python 3.7.10
pip 21.2.4

Also, MSMS is installed and added to Path in Windows.

**Comment by swanss** [comment]
I'm seeing the same error when attempting to install PyVol

**Comment by jedgold** [comment]
Just to pile on: I have the same error, using incentive PyMol (same as gorostiolam)

**Comment by tjmier** [comment]
I am also having the same issue when attempting to launch the plugin 
Win10 
pymol 2.5.4
python 3.11
installed via plugin manager using "https://github.com/schlessinger-lab/pyvol/blob/master/installers/pyvol-installer.zip"
![Capture](https://user-images.githubusercontent.com/120520360/208523804-b64c7b4b-86d5-4478-8e8a-72255af059a5.PNG)
