### ISSUE TITLE
Can't install PyVOL

### ISSUE THREAD

**Issue by SilentGene** [schlessingerlab/pyvol#6]
Hi, when I click the button 'Install PyVOL from PYPI', I ran into this error:
```
Cannot load PyMOL plugins module
Traceback (most recent call last):
  File "D:\BioPrograms\PyMOL\lib\site-packages\pmg_tk\startup\pyvol_gui\__init__.py", line 373, in <lambda>
    form.install_remote_button.clicked.connect(lambda: install_remote_pyvol(form))
  File "D:\BioPrograms\PyMOL\lib\site-packages\pmg_tk\startup\pyvol_gui\__init__.py", line 106, in install_remote_pyvol
    install_pypi_pyvol()
  File "D:\BioPrograms\PyMOL\lib\site-packages\pmg_tk\startup\pyvol_gui\__init__.py", line 100, in install_pypi_pyvol
    refresh_installation_status(form)
NameError: name 'form' is not defined
```
BTW, My PyMOL is running on Windows10. What can I do solve this problem?

Thanks,
Heyu

**Comment by rhs2132** [comment]
There was a typo in that function that is now fixed. Uninstall the GUI using the plugin manager and reinstall using 1.6.8. Let me know if that fixes the issue.

**Comment by ma2thias** [comment]
Hi
I have always a MSMS installation problem. Tried all options including "custom" and set the path to msms.MacOSX.2.6.1 Still left wurh MSMS path: not found.
Yes, working on a Mac (Mojave). During startup PyMol also prints "Cannot load PyMOL plugins module". 
Any idea what I do wrong?
Thanks, Matthias
